version: '3.4'

networks:
   backend:

services:
   customerdb:
     container_name: customer-db
     image: mcr.microsoft.com/azure-sql-edge
     environment:
       - ACCEPT_EULA=Y
       - SA_PASSWORD=your_password123
     networks:
       - backend
     ports:
       - 8001:1433
   customerwebapi:
     image: ${DOCKER_REGISTRY-}customerwebapi
     build:
       context: .
       dockerfile: Microservices/CustomerWebApi/Dockerfile
     networks:
       - backend
     ports:
       - 8002:80
     environment:
       - DB_HOST=customerdb
       - DB_NAME=customer
       - DB_SA_PASSWORD=your_password123